### ISSUE TITLE
[Feature request] Add "none" or "proprietary" license for internal packages

### ISSUE THREAD

**Issue by rhys-vdw** [nomnomab/New-Package-Helper#1]
Would be nice to have this option for packages that are shared within an organization by a private git server.

**Comment by nomnomab** [comment]
The `none` license is straightforward to add, but what would you suggest for the `proprietary` one? The `licenseUrl` field can point to w/e url, or local path, your internal license is at. Unless you'd want a `TextAsset` field to drop in a license file manually (and for it to get auto-copied into the output folder)?

**Comment by rhys-vdw** [comment]
I think just the word "proprietary" is fine. Generally you'd just include a LICENSE.md in the repo regardless of that field so there's no need to link it from the package.json. It's mainly so you're not forced to pick a mismatched license.

**Comment by rhys-vdw** [comment]
I guess another solution would be to just to add an "other" to drop the dropdown and then expose a text field?

**Comment by nomnomab** [comment]
Added 👍 Thanks for the clarification.
